noticiasAuto/Models/Noticias.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace noticiasAuto.Models
{
    public class Noticias
    {
        public Noticias()
        {
            ListaDeEquipas = new HashSet<Equipas>();
            ListaDeComentarios = new HashSet<Comentarios>();
        }

        [Key]
        public int IdNoticia { get; set; }

        public string Fotografia { get; set; }

        public string Titulo { get; set; }

        public string Conteudo { get; set; }

        [ForeignKey("Utilizadores")]
        public int UserFK { get; set; }
        public virtual utilizadores Utilizadores { get; set; }

        public virtual ICollection<Equipas> ListaDeEquipas{ get; set; }

        public virtual ICollection<Comentarios> ListaDeComentarios { get; set; }


    }
}

noticiasAuto/Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using noticiasAuto.Models;

namespace noticiasAuto.Controllers
{
    public class NoticiasController : Controller
    {
        private NoticiasDB db = new NoticiasDB();

        // GET: Noticias
        public ActionResult Index()
        {
            var noticias = db.Noticias.Include(n => n.Utilizadores);
            return View(noticias.ToList());
        }

        // GET: Noticias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noticias noticias = db.Noticias.Find(id);
            if (noticias == null)
            {
                return HttpNotFound();
            }
            return View(noticias);
        }

        // GET: Noticias/Create
        public ActionResult Create()
        {
            ViewBag.UserFK = new SelectList(db.Utilizadores, "IdUser", "Nome");
            return View();
        }

        // POST: Noticias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdNoticia,Fotografia,Titulo,Conteudo,UserFK")] Noticias noticias)
        {
            if (ModelState.IsValid)
            {
                db.Noticias.Add(noticias);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserFK = new SelectList(db.Utilizadores, "IdUser", "Nome", noticias.UserFK);
            return View(noticias);
        }

        // GET: Noticias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noticias noticias = db.Noticias.Find(id);
            if (noticias == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserFK = new SelectList(db.Utilizadores, "IdUser", "Nome", noticias.UserFK);
            return View(noticias);
        }

        // POST: Noticias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdNoticia,Fotografia,Titulo,Conteudo,UserFK")] Noticias noticias)
        {
            if (ModelState.IsValid)
            {
                db.Entry(noticias).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserFK = new SelectList(db.Utilizadores, "IdUser", "Nome", noticias.UserFK);
            return View(noticias);
        }

        // GET: Noticias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Noticias noticias = db.Noticias.Find(id);
            if (noticias == null)
            {
                return HttpNotFound();
            }
            return View(noticias);
        }

        // POST: Noticias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Noticias noticias = db.Noticias.Find(id);
            db.Noticias.Remove(noticias);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

noticiasAuto/Views/Noticias/Create.cshtml
@model noticiasAuto.Models.Noticias

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Noticias</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Conteudo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Conteudo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Conteudo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserFK, "UserFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

noticiasAuto/Views/Noticias/Delete.cshtml
@model noticiasAuto.Models.Noticias

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Noticias</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Utilizadores.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Utilizadores.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fotografia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Conteudo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Conteudo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

noticiasAuto/Views/Noticias/Details.cshtml
@model noticiasAuto.Models.Noticias

@{
    ViewBag.Title = "Details";
}



<div>
    <hr />

    <div>
        <a href="~/imagens/@Model.Fotografia" target="_blank">
            <img class="img-responsive" style="max-height:300px; margin:0 auto; " src="~/imagens/@Model.Fotografia" />
        </a>
    </div>
    <br />
    <h2 style="font-weight:bold">@Model.Titulo</h2>
    <p style="font-size: 16px; text-align: justify;">@Model.Conteudo</p>
    <br />
    <p>Autor da notícia: @Model.Utilizadores.Nome</p>

</div>


<h4>Comentários:</h4>
@foreach (var comentarios in Model.ListaDeComentarios)
{
        //ADICIONAR DATA DE COMENTARIO
    <h6>@comentarios.Utilizador.Nome </h6>
    <p>@comentarios.Conteudo</p>
    <hr />

}
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.IdNoticia }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

noticiasAuto/Views/Noticias/Edit.cshtml
@model noticiasAuto.Models.Noticias

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Noticias</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdNoticia)

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Conteudo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Conteudo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Conteudo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserFK, "UserFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

noticiasAuto/Views/Noticias/Index.cshtml
@model IEnumerable<noticiasAuto.Models.Noticias>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<<

@foreach (var noticias in Model)
{
    <div class="col-sm-4" style="text-align: center; justify-content: center; padding-bottom:20px; ">
        <div class="thumbnail" style="height:250px; width:350px;" onclick="window.location= '@Url.Action("Details","Noticias", new { id = noticias.IdNoticia})'">

            <img src="~/imagens/@noticias.Fotografia" alt="" class="image" style="align-content:center; height:240px; width:340px">

            <h5 style="position: absolute; top: 200px; left: 15px; right:15px; ">
                <p style="color:white"><strong> @noticias.Titulo</strong></p>
            </h5>
        </div>
    </div>

}