noticiasAuto/Models/Equipas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace noticiasAuto.Models
{
    public class Equipas
    {
        public Equipas()
        {
            ListaDePilotos = new HashSet<Pilotos>();
            ListaDeNoticias = new HashSet<Noticias>();
        }

        [Key]
        public int IdEquipa { get; set; }

        public string Nome { get; set; }

        public DateTime DataFundacao { get; set; }

        public string Logo { get; set; }

        public string Fundador { get; set; }

        public string Nacionalidade { get; set; }

        public virtual ICollection<Pilotos> ListaDePilotos { get; set; }

        public virtual ICollection<Noticias> ListaDeNoticias{ get; set; }

    }
}

noticiasAuto/Controllers/EquipasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using noticiasAuto.Models;

namespace noticiasAuto.Controllers
{
    public class EquipasController : Controller
    {
        private NoticiasDB db = new NoticiasDB();

        // GET: Equipas
        public ActionResult Index()
        {
            return View(db.Equipas.ToList());
        }

        // GET: Equipas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipas equipas = db.Equipas.Find(id);
            if (equipas == null)
            {
                return HttpNotFound();
            }
            return View(equipas);
        }

        // GET: Equipas/Create
        // GET: Equipas/Create
        public ActionResult Create()
        {
            return View(); 
        }
        // POST: Equipas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IdEquipa,Nome,DataFundacao,Logo,Fundador,Nacionalidade")] Equipas equipas, HttpPostedFileBase fileUploadFotografia)
        {

            // determinar o ID do novo Agente
            int novoID = 0;
            // *****************************************
            // proteger a geração de um novo ID
            // *****************************************
            // determinar o nº de tipo de pratos na tabela
            if (db.Equipas.Count() == 0)
            {
                novoID = 1;
            }
            else
            {
                novoID = db.Equipas.Max(a => a.IdEquipa) + 1;
            }
            // atribuir o ID ao novo agente
            equipas.IdEquipa = novoID;
            // ***************************************************
            // outra hipótese possível seria utilizar o
            // try { }
            // catch(Exception) { }
            // ***************************************************

            // var. auxiliar
            string nomeFotografia = "equipas" + novoID + ".jpg";
            string caminhoParaFotografia = Path.Combine(Server.MapPath("~/Imagens/"), nomeFotografia); // indica onde a imagem será guardada

            // verificar se chega efetivamente um ficheiro ao servidor
            if (fileUploadFotografia != null)
            {
                // guardar o nome da imagem na BD
                equipas.Logo = nomeFotografia;
            }
            else
            {
                // não há imagem...
                ModelState.AddModelError("", "Não foi fornecida uma imagem..."); // gera MSG de erro
                return View(equipas); // reenvia os dados do 'Agente' para a View
            }

            if (ModelState.IsValid)
            {
                // guardar a imagem no disco rígido
                fileUploadFotografia.SaveAs(caminhoParaFotografia);
                db.Equipas.Add(equipas);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(equipas);
        }


        // GET: Equipas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipas equipas = await db.Equipas.FindAsync(id);
            if (equipas == null)
            {
                return HttpNotFound();
            }
            return View(equipas);
        }

        // POST: Equipas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IdEquipa,Nome,DataFundacao,Logo,Fundador,Nacionalidade")] Equipas equipas, HttpPostedFileBase uploadFoto)

        {
            // vars. auxiliares
            string novoNome = "";
            string nomeAntigo = "";

            if (ModelState.IsValid)
            {
                try
                {              /// se foi fornecida uma nova imagem,
                               /// preparam-se os dados para efetuar a alteração
                    if (uploadFoto != null)
                    {
                        /// antes de se fazer alguma coisa, preserva-se o nome antigo da imagem,
                        /// para depois a remover do disco rígido do servidor
                        nomeAntigo = equipas.Logo;
                        /// para o novo nome do ficheiro, vamos adicionar o termo gerado pelo timestamp
                        /// devidamente formatado, mais
                        /// A extensão do ficheiro é obtida automaticamente em vez de ser escrita de forma explícita
                        novoNome = "equipa" + equipas.IdEquipa + DateTime.Now.ToString("_yyyyMMdd_hhmmss") + Path.GetExtension(uploadFoto.FileName).ToLower(); ;
                        /// atualizar os dados do Agente com o novo nome
                        equipas.Logo = novoNome;
                        /// guardar a nova imagem no disco rígido
                        uploadFoto.SaveAs(Path.Combine(Server.MapPath("~/Imagens/"), novoNome));
                    }

                    // guardar os dados do Agente
                    db.Entry(equipas).State = EntityState.Modified;
                    // Commit
                    db.SaveChanges();

                    /// caso tenha sido fornecida uma nova imagem há necessidade de remover 
                    /// a antiga
                    if (uploadFoto != null)
                        System.IO.File.Delete(Path.Combine(Server.MapPath("~/images/"), nomeAntigo));


                    // enviar os dados para a página inicial
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    // caso haja um erro deve ser enviada uma mensagem para o utilizador
                    //ModelState.AddModelError("", string.Format("Ocorreu um erro com a edição dos dados do tipo de Prato {0}", equipas.Nome));
                    return RedirectToAction("Index");
                }
            }
            return View(equipas);
        }




        // POST: Equipas/Delete/5


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");
            }
            Equipas equipa = db.Equipas.Find(id);
            if (equipa == null)
            {
                return HttpNotFound();
            }
            return View(equipa);
        }

        // POST: Equipas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //procurar a Equipa
            Equipas equipas = db.Equipas.Find(id);

            try
            {
                //remover da memória
                db.Equipas.Remove(equipas);
                //commit na BD
                db.SaveChanges();
                System.IO.File.Delete(Path.Combine(Server.MapPath("~/Imagens/"), equipas.Logo));
                return RedirectToAction("Index");

            }
            catch (Exception)
            {
                //gerar uma mensagem de erro, a ser aprentada ao utilizador
                ModelState.AddModelError("", string.Format("Não foi possível remover a Equipa, porque existem notícias associadas a ela.", id));
                //reenviar os dados para a View
            }
            return View(equipas);

        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

noticiasAuto/Controllers/PilotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using noticiasAuto.Models;

namespace noticiasAuto.Controllers
{
    public class PilotosController : Controller
    {
        private NoticiasDB db = new NoticiasDB();

        // GET: Pilotos
        public ActionResult Index()
        {
            var pilotos = db.Pilotos.Include(p => p.Equipa);
            return View(pilotos.ToList());
        }

        // GET: Pilotos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilotos pilotos = db.Pilotos.Find(id);
            if (pilotos == null)
            {
                return HttpNotFound();
            }
            return View(pilotos);
        }

        // GET: Pilotos/Create
        public ActionResult Create()
        {
            ViewBag.EquipaFK = new SelectList(db.Equipas, "IdEquipa", "Nome");
            return View();
        }

        // POST: Pilotos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPiloto,Nome,DataNascimento,Nacionalidade,Fotografia,EquipaFK")] Pilotos pilotos, string DataNascimento, HttpPostedFileBase fileUploadLogo)
        {
            string nomeFoto = "Piloto" + DateTime.Now.ToString("_yyyyMMdd_hhmmss") + ".jpg";
            string pathFoto = Path.Combine(Server.MapPath("~/Imagens/"), nomeFoto);

            //caso chegue efectivamente um ficheiro ao servidor
            if ((fileUploadLogo != null) && (fileUploadLogo.ContentType.ToString() == "image/jpeg"))
            {
                //guardar na BD
                pilotos.Fotografia = nomeFoto;
            }
            else
            {
                // não há imagem...
                ModelState.AddModelError("", "Não foi fornecida uma imagem ou o ficheiro inserido não é JPG...");
                return View(pilotos);
            }

            DateTime dataNasci = DateTime.Parse(DataNascimento);
            pilotos.DataNascimento = dataNasci;

            if (ModelState.IsValid)
            {
                db.Pilotos.Add(pilotos);
                db.SaveChanges();

                fileUploadLogo.SaveAs(pathFoto);

                return RedirectToAction("Details", "Equipas", new { id = pilotos.EquipaFK });

            }

            ViewBag.EquipaFK = new SelectList(db.Equipas, "IdEquipa", "Nome", pilotos.EquipaFK);
            return View(pilotos);
        }

        // GET: Pilotos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Equipas");
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilotos pilotos = db.Pilotos.Find(id);
            if (pilotos == null)
            {
                return HttpNotFound();
            }
            ViewBag.EquipaFK = new SelectList(db.Equipas, "IdEquipa", "Nome", pilotos.EquipaFK);
            return View(pilotos);
        }

        // POST: Pilotos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idPiloto,EquipaFK,Nome,DataNascimento,Nacionalidade,Fotografia")] Pilotos pilotos, string DataNascimento, HttpPostedFileBase fileUploadLogo, string fileUploadLogoAntigo)
        {
            ViewBag.EquipaFK = new SelectList(db.Equipas, "idEquipa", "Nome", pilotos.EquipaFK);

            DateTime dataNasci = DateTime.Parse(DataNascimento);
            pilotos.DataNascimento = dataNasci;


            string nomeFotografia = "Piloto" + pilotos.IdPiloto + DateTime.Now.ToString("_yyyyMMdd_hhmmss") + ".jpg";
            string oldName = fileUploadLogoAntigo;
            string caminhoParaLogo = Path.Combine(Server.MapPath("~/Imagens/"), nomeFotografia);



            //verificar se chega efetivamente um ficheiro ao servidor
            if ((fileUploadLogo != null) && (fileUploadLogo.ContentType.ToString() == "image/jpeg"))
            {
                //guardar o nome da imagem na BD
                pilotos.Fotografia = nomeFotografia;
            }
            else
            {
                pilotos.Fotografia = oldName;
                // não há imagem...
                ModelState.AddModelError("", "Não foi fornecida uma imagem ou o ficheiro inserido não é JPG...");

                return View(pilotos);
            }


            if (ModelState.IsValid)
            {
                db.Entry(pilotos).State = EntityState.Modified;
                db.SaveChanges();
            }
            if (fileUploadLogo != null)
            {
                //guardar o nome da imagem na BD
                fileUploadLogo.SaveAs(caminhoParaLogo);
                System.IO.File.Delete(Path.Combine(Server.MapPath("~/Imagens/"), oldName));
            }



            ViewBag.EquipaFK = new SelectList(db.Equipas, "idEquipa", "Nome", pilotos.EquipaFK);
            return RedirectToAction("Details", "Equipas", new { id = pilotos.EquipaFK });
        }

        // GET: Pilotos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilotos pilotos = db.Pilotos.Find(id);
            if (pilotos == null)
            {
                return HttpNotFound();
            }
            return View(pilotos);
        }

        // POST: Pilotos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pilotos pilotos = db.Pilotos.Find(id);
            db.Pilotos.Remove(pilotos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

noticiasAuto/Views/Equipas/Create.cshtml
@model noticiasAuto.Models.Equipas

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create",
                      "equipas",
                      FormMethod.Post,
                      new { enctype = "multipart/form-data" }
                      ))
{@Html.AntiForgeryToken()

<script>
    function funcao1() {
        alert("Equipa Criada!");
    }
</script>


<div class="form-horizontal">
    <h4>Equipas</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            Nome da Equipa:
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            Data de Fundação:
            <input class="form-control" type="date" style="width:160px" name="DataFundacao" min="1900-01-01" required pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" max=@DateTime.Now.ToString("yyyy-MM-dd") />

            @Html.ValidationMessageFor(model => model.DataFundacao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">

        <div class="col-md-10">
            Logotipo da Equipa:
            <input type="file"
                   name="fileUploadFotografia"
                   style="color:blue;"
                   accept=".jpg" />
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-10">
            Fundador
            @Html.EditorFor(model => model.Fundador, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fundador, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            Nacionalidade:
            @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Criar Equipa" class="btn btn-success" onclick="funcao1()" />        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

noticiasAuto/Views/Equipas/Delete.cshtml
@model noticiasAuto.Models.Equipas

@{
    ViewBag.Title = "Delete";
}

    <div class="alert alert-danger" role="alert" style='font-weight:bold;'>
        Deseja mesmo eliminar a equipa  @Html.DisplayFor(model => model.Nome)?
    </div>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Nome:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>

            <dt>
                Data de Fundação:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DataFundacao)
            </dd>

            <dt>
                    Sede:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nacionalidade)
            </dd>

            <dt>
                Fundador da equipa:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fundador)
            </dd>

            <dt>
                Logotipo:
            </dt>

            <dd>
                <a href="~/Imagens/@Model.Logo" target="_blank">
                    <img src="~/Imagens/@Model.Logo" class="rounded" height="150" width="200" />
                </a>
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" onclick="javascript:return ConfirmMessageBox();" @Html.DisplayFor(model => model.Nome) ? />               
        @Html.ActionLink("Voltar para a Lista de Equipas", "Index")
    </div>

            <script>
        function ConfirmMessageBox() {
            var result = confirm("Pretende mesmo eliminar a equipa @Html.DisplayFor(model => model.Nome)?");
            if (result) {
                return true;
            } else {
                return false;
            }
        }

/**/</script>
        }
    </div>

noticiasAuto/Views/Equipas/Details.cshtml
@model noticiasAuto.Models.Equipas

@{
    ViewBag.Title = "Details";
}

    <div class="alert alert-warning" role="alert">
        <h1>Detalhes da Equipa:</h1> @Html.DisplayFor(model => model.Nome)
    </div>

<div>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            Nome da Equipa:
            @*Html.DisplayNameFor(model => model.Nome)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            Data de Fundação:

            @*Html.DisplayNameFor(model => model.DataFundacao)*@
        </dt>

        <dd>
            @Convert.ToDateTime(Model.DataFundacao).ToString("dd/MM/yyyy")
        </dd>

        <dt>
            Sede:
            @*Html.DisplayNameFor(model => model.Nacionalidade)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidade)
        </dd>


        <dt>
            Fundador da Equipa:
            @*Html.DisplayNameFor(model => model.Fundador)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fundador)
        </dd>


        <dt>
            Fotografia da Equipa:
            @*Html.DisplayNameFor(model => model.Logo)*@
        </dt>

        <dd>
            <a href="~/Imagens/@Model.Logo" target="_parent">
                <img src="~/Imagens/@Model.Logo" class="rounded" height="100" width="" />
            </a>
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Editar Piloto", "Edit", new { id = Model.IdEquipa }) |
    @Html.ActionLink("Eliminar Equipa", "Delete", new { id = Model.IdEquipa }) |
    @Html.ActionLink("Voltar para a lista de Equipas", "Index")
</p>

<div style="clear: left">
    <div class="alert alert-info" role="alert">

        <font style='font-weight:bold;'> Pilotos da Equipa @Html.DisplayFor(model => model.Nome)</font>
    </div>
    @foreach (var pilotos in Model.ListaDePilotos)
    {
        <div class="col-lg-4" style=" text-align: center; padding-bottom:30px;">
            <div>@pilotos.Nome</div>
            <a href="@Url.Action("Details","Pilotos", new { id=pilotos.IdPiloto } )">
                <img src="~/imagens/@pilotos.Fotografia" height="120" width="190" />
            </a>
        </div>

    }
</div>

noticiasAuto/Views/Equipas/Edit.cshtml
@model noticiasAuto.Models.Equipas

@{
    ViewBag.Title = "Edit";
}


@*
    Quando se deseja efetuar o upload de um ficheiro,
    esta instrução é insuficiente
    @using(Html.BeginForm())
    é necessário adicionar-lhe o parâmetro 'enctype = "multipart/form-data" '
*@
@using (Html.BeginForm("Edit",
                      "Equipas",
                      FormMethod.Post,
                      new { enctype = "multipart/form-data" }))
{



    @Html.AntiForgeryToken()






    <div class="form-horizontal">
        <h4>Equipas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdEquipa)


        <div class="form-group">
            <div class="col-md-10">
                Nome:
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                Data de Fundação:
                @Html.EditorFor(model => model.DataFundacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataFundacao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
           
            <div class="col-md-10">
                @* Mostrar a imagem associada a equpa *@
                <a href="~/Imagens/@Model.Logo" target="_blank">
                    <img src="~/Imagens/@Model.Logo" height="150" />
                </a>
                @* procurar a nova imagem*@
                <input type="file" name="uploadFoto" style="color:blue;" accept=".jpg" />

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                Fundador:
                @Html.EditorFor(model => model.Fundador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fundador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                Sede:
                @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Equipa" class="btn btn-success" />
            </div>
        </div>

    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

noticiasAuto/Views/Equipas/Index.cshtml
@model IEnumerable<noticiasAuto.Models.Equipas>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Criar Equipa", "Create")
</p>



@foreach (var item in Model)
{
    <div class="col-sm-4" style="text-align:center; justify-content: center; padding-bottom:20px ">
        <div class="thumbnail" style="height:200px; width:300px;" onclick="window.location= '@Url.Action("Details","Equipas", new { id = item.IdEquipa})'">
            <img src="~/imagens/@item.Logo" alt="" style="align-content:center; height:200px; width:300px">

            
            
        </div>
    </div>
}